[package]
name = "whim-optimizer"
description = "Bytecode optimization for Whim"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[lints]
workspace = true

[dependencies]
hashbrown = { workspace = true }
itoa = { workspace = true }
ryu = { workspace = true }
whim-base = { workspace = true }
whim-bytecode = { workspace = true }
whim-span = { workspace = true }
whim-value = { workspace = true }
