[package]
name = "whim-macros"
description = "Macros for declaring Whim's Rust-backed core symbols"
version.workspace = true
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true
publish.workspace = true

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
proc-macro2 = { workspace = true }
quote = { workspace = true }
syn = { workspace = true }
target-guard = { workspace = true }
whim-syn = { workspace = true }

[dev-dependencies]
trybuild = { workspace = true }
