pub use libc::{
    AF_INET, AF_INET6, AF_UNIX, EACCES, EAGAIN, EEXIST, EINVAL, EISDIR, ENOENT, ENOTDIR, ENOTEMPTY,
    EPERM, IPPROTO_IPV6, IPPROTO_TCP, IPV6_V6ONLY, LOCK_EX, LOCK_SH, LOCK_UN, O_APPEND, O_CLOEXEC,
    O_CREAT, O_EXCL, O_RDONLY, O_RDWR, O_TRUNC, O_WRONLY, RLIMIT_AS, RLIMIT_CORE, RLIMIT_CPU,
    RLIMIT_DATA, RLIMIT_FSIZE, RLIMIT_NOFILE, RLIMIT_STACK, S_IFBLK, S_IFCHR, S_IFDIR, S_IFIFO,
    S_IFLNK, S_IFMT, S_IFREG, S_IFSOCK, SEEK_CUR, SEEK_END, SEEK_SET, SIGABRT, SIGALRM, SIGBUS,
    SIGCHLD, SIGCONT, SIGFPE, SIGHUP, SIGILL, SIGINT, SIGIO, SIGKILL, SIGPIPE, SIGPROF, SIGQUIT,
    SIGSEGV, SIGSTOP, SIGSYS, SIGTERM, SIGTRAP, SIGTSTP, SIGTTIN, SIGTTOU, SIGURG, SIGUSR1,
    SIGUSR2, SIGVTALRM, SIGWINCH, SIGXCPU, SIGXFSZ, SO_BROADCAST, SO_RCVBUF, SO_REUSEADDR,
    SO_REUSEPORT, SO_SNDBUF, SOCK_DGRAM, SOCK_STREAM, SOL_SOCKET, TCP_NODELAY,
};

#[cfg(target_os = "linux")]
pub use libc::{SIGPWR, SIGSTKFLT};
#[cfg(not(target_os = "linux"))]
pub const SIGSTKFLT: i32 = -1;
#[cfg(not(target_os = "linux"))]
pub const SIGPWR: i32 = -2;
